"""Combattants + movesets (Grille des Combos & Signatures).

Formule d'éjection (spec moteur) : Force = BaseKnockback + Pourcentage * KnockbackScaling
  - Attaques légères (P) : bkb faible, kbs ~0  -> combos
  - Signatures (S)       : bkb moyen, kbs élevé -> éjection, chargeables (x1.0 -> x1.5)
angle : 0 = horizontal vers l'avant, 90 = vers le haut, <0 = vers le bas, >90 = vers l'arrière.
Temps en secondes. Hitbox : taille (avant, haut) et décalage (avant, haut) depuis le centre du perso.
"""

HB = {  # hitbox par défaut de chaque gabarit d'animation : (taille_x, taille_y), (avant, haut)
    "jab": ((4.0, 3.0), (2.2, 0.6)), "hook": ((5.0, 3.6), (2.3, 0.6)), "uppercut": ((3.6, 5.0), (1.8, 1.6)),
    "overhead": ((4.6, 4.6), (2.3, 0.6)), "kick": ((4.6, 3.0), (2.7, 0.0)), "sidekick": ((5.2, 3.0), (2.9, 0.3)),
    "sweep": ((6.2, 2.0), (2.2, -1.8)), "stomp": ((4.0, 2.6), (1.9, -1.8)), "thrust": ((7.0, 2.6), (3.7, 0.5)),
    "spin": ((7.0, 6.0), (0.0, 0.0)), "bodyslam": ((4.6, 4.2), (2.4, 0.0)), "airkick": ((5.0, 3.6), (2.5, -0.5)),
    "airdown": ((3.6, 4.0), (0.6, -2.6)), "cast": ((5.0, 4.0), (2.8, 0.6)), "dash": ((4.2, 4.2), (1.9, 0.0)),
    "charge": ((4.2, 4.6), (2.0, 0.0)), "counter": ((4.4, 4.0), (2.3, 0.5)), "throw": ((3.0, 3.0), (2.0, 1.0)),
    "trap": ((3.0, 2.0), (2.5, -2.0)), "drink": ((3.0, 3.0), (1.5, 0.5)), "roar": ((9.0, 7.0), (0.0, 0.5)),
    "recovery": ((4.0, 6.0), (0.8, 1.5)), "groundpound": ((4.0, 5.0), (0.5, -1.5)), "grab": ((3.6, 3.6), (2.0, 0.4)),
}

def _base(name, desc, anim, defaults, kw):
    m = dict(defaults)
    m.update({"name": name, "desc": desc, "anim": anim})
    size, off = HB.get(anim, ((4.0, 4.0), (2.0, 0.5)))
    m.setdefault("hb", list(size))
    m.setdefault("off", list(off))
    m.update(kw)
    if "hb" in kw: m["hb"] = list(kw["hb"])
    if "off" in kw: m["off"] = list(kw["off"])
    return m

def L(name, desc, anim, **kw):
    """Attaque légère (bouton P)."""
    d = {"kind": "melee", "dmg": 4, "bkb": 9, "kbs": 0.04, "angle": 25, "startup": 0.09, "active": 0.07,
         "recovery": 0.17, "hits": 1, "charge": False, "heavy": False}
    return _base(name, desc, anim, d, kw)

def S(name, desc, anim, **kw):
    """Signature (bouton S) : chargeable."""
    d = {"kind": "melee", "dmg": 13, "bkb": 26, "kbs": 0.55, "angle": 40, "startup": 0.26, "active": 0.1,
         "recovery": 0.38, "hits": 1, "charge": True, "heavy": True}
    return _base(name, desc, anim, d, kw)

def proj(**kw):
    p = {"speed": 70, "grav": 0, "size": 1.2, "life": 1.2, "shape": "Ball", "color": "#ffffff", "mat": "Neon"}
    p.update(kw)
    return p

def rec(vy=75, vx=8, **kw):
    return dict(kind="recovery", vy=vy, vx=vx, **kw)

def gp(vy=-95, vx=0, radius=6.5, **kw):
    return dict(kind="groundpound", vy=vy, vx=vx, radius=radius, **kw)

# ---------------------------------------------------------------------------
# Moveset commun « mains nues » (avant de ramasser la Caisse Bizarre)
# ---------------------------------------------------------------------------
UNARMED = {
    "Pn": L("Direct-direct", "Deux directs rapides.", "jab", hits=2, dmg=3),
    "Ps": L("Crochet", "Crochet large vers l'avant.", "hook", dmg=5, angle=20, bkb=11),
    "Pd": L("Balayette", "Balayage bas qui soulève un peu.", "sweep", dmg=4, angle=70, bkb=12),
    "PairN": L("Toupie", "Tourne sur lui-même en l'air.", "spin", dmg=4, hits=2),
    "PairS": L("Coup de pied sauté", "Coup de pied tendu en l'air.", "airkick", dmg=5),
    "PairD": L("Écrase-tête", "Talon vers le bas.", "airdown", dmg=5, angle=-55),
    "Sn": S("Uppercut", "Uppercut puissant (anti-air).", "uppercut", dmg=12, angle=80),
    "Ss": S("Coup d'épaule", "Charge à l'épaule vers l'avant.", "charge", kind="dash", speed=48, dur=0.35, dmg=12, angle=30),
    "Sd": S("Frappe au sol", "Coup de poing dans le sol, onde courte.", "stomp", kind="aura", radius=5.5, dmg=11, angle=70),
    "Sup": S("Saut de l'ange", "Remontée avec un uppercut.", "recovery", dmg=8, angle=85, bkb=18, kbs=0.25, **rec(72, 6)),
    "SairD": S("Chute lourde", "Se laisse tomber de tout son poids.", "groundpound", dmg=12, angle=55, **gp()),
}

# ---------------------------------------------------------------------------
# Les 20 combattants
# ---------------------------------------------------------------------------
FIGHTERS = [
 {"key": "gege", "num": 1, "name": "Gégé le Pochtron", "style": "Piégeur imprévisible", "diff": 2, "launch": True,
  "weapon": "Bouteille de soda douteux", "passive": "bulles", "passiveName": "Jauge de Bulles",
  "passiveDesc": "↓S remplit une gorgée (3 max). Chaque gorgée : +10 % de dégâts. À 3, l'Haleine-briquet inverse les commandes.",
  "weight": 1.0, "arena": "bar",
  "moves": {
   "Pn": L("Coup de goulot + savate molle", "Coup de goulot rapide enchaîné d'une savate molle.", "jab", hits=2, dmg=3),
   "Ps": L("Revers de bouteille", "Revers de bouteille ample vers l'avant.", "hook", dmg=5, angle=20, bkb=11),
   "Pd": L("Croche-patte titubant", "Croche-patte en titubant. Envoie l'adversaire légèrement en l'air.", "sweep", dmg=4, angle=72, bkb=13),
   "PairN": L("Bouteille plongeante", "Coup de bouteille de haut en bas en l'air.", "overhead", dmg=5, angle=-30),
   "PairS": L("Ruade titubante", "Ruade en l'air.", "airkick", dmg=5),
   "PairD": L("Chute genou en avant", "Tombe genou en avant.", "airdown", dmg=5, angle=-60),
   "Sn": S("Haleine-briquet", "Flamme cartoon devant lui (inverse les commandes si passif chargé).", "cast", hb=(6.5, 3.2), off=(3.6, 0.6),
           hits=3, dmg=12, angle=35, extra="gegeFlame", vfx="#ff7b00"),
   "Ss": S("Titubade folle", "Avance en zigzag avec super-armure, finit par un gros coup de bouteille.", "charge", kind="dash",
           speed=42, dur=0.5, armor=True, dmg=14, angle=35),
   "Sd": S("Petite gorgée", "Boit (charge le passif) et crache une flaque glissante au sol.", "drink", kind="trap", life=6, trapSize=(6, 1),
           dmg=3, bkb=6, kbs=0.05, angle=60, status="slip", statusDur=2.5, extra="gorgee", vfx="#b7ff3b"),
   "Sup": S("Le Lampadaire", "Un lampadaire pousse du vide, il s'y accroche et se propulse en l'air.", "recovery", dmg=9, angle=85,
            bkb=18, kbs=0.25, **rec(80, 4)),
   "SairD": S("Plongeon du comptoir", "Tombe à plat ventre, créant une onde de choc pétillante.", "groundpound", dmg=13, angle=50,
              **gp(-95, 0, 7)),
  }},
 {"key": "mamie", "num": 2, "name": "Mamie Tricot", "style": "Zoneuse", "diff": 3, "launch": True,
  "weapon": "Sac à main & Canne", "passive": "pelotes", "passiveName": "Pelotes-pièges",
  "passiveDesc": "Jusqu'à 3 pelotes-pièges au sol en même temps : elles ligotent 1 s.", "weight": 0.85, "arena": "salon",
  "moves": {
   "Pn": L("Sac à main + pincement", "Coup de sac à main suivi d'un pincement de joue.", "jab", hits=2, dmg=3),
   "Ps": L("Aiguille à tricoter", "Long coup d'aiguille en estoc. Très bonne allonge.", "thrust", dmg=5, hb=(7.5, 2.2), off=(4.0, 0.6)),
   "Pd": L("Balayage de canne", "Balayage de canne au ras du sol.", "sweep", dmg=4, angle=72, bkb=12),
   "PairN": L("Parapluie tournoyant", "Parapluie qui tournoie autour d'elle.", "spin", hits=3, dmg=2),
   "PairS": L("Pantoufle jetée", "Pantoufle jetée courte.", "throw", kind="projectile", dmg=4,
              proj=proj(speed=60, life=0.45, size=0.9, shape="Block", color="#ff9ff3", mat="Fabric")),
   "PairD": L("Dentier mordant", "Le dentier mord vers le bas.", "airdown", hits=2, dmg=3, angle=-50),
   "Sn": S("Lancer de chat", "Envoie un chat en cloche (anti-air). Le chat donne 3 coups de griffes.", "throw", kind="projectile",
           dmg=12, angle=70, hits=3, proj=proj(speed=55, grav=60, up=0.9, life=1.4, size=1.4, color="#e67e22", mat="Fabric")),
   "Ss": S("Charge du déambulateur", "Sort un déambulateur et fonce devant elle. Hitbox continue.", "dash", kind="dash",
           speed=34, dur=0.6, dmg=12, angle=30),
   "Sd": S("Pose de pelote", "Dépose un piège qui ligote temporairement l'adversaire qui marche dessus.", "trap", kind="trap",
           life=10, trapSize=(2.5, 2), dmg=4, bkb=4, kbs=0, angle=80, status="root", statusDur=1.0, maxTraps=3, vfx="#c77dba"),
   "Sup": S("Envol de châle", "Ouvre son châle comme un parachute et s'envole en diagonale haute.", "recovery", dmg=7, angle=70,
            bkb=16, kbs=0.2, glide=True, **rec(62, 30)),
   "SairD": S("Pluie de bonbons", "Plonge en diagonale en dispersant des bonbons durs à la menthe.", "groundpound", dmg=11, angle=45,
              extra="candies", **gp(-70, 40, 6)),
  }},
 {"key": "dylan", "num": 3, "name": "Dylan le Livreur", "style": "Rushdown", "diff": 2, "launch": True,
  "weapon": "Trottinette & Sac Cube", "passive": "note", "passiveName": "Note client",
  "passiveDesc": "Note de 1 à 5 ★ : chaque touche donnée +1 ★, chaque coup reçu -1 ★. +5 % de vitesse par étoile.",
  "weight": 0.95, "arena": "parking",
  "moves": {
   "Pn": L("Klaxon + sac isotherme", "Jab de klaxon enchaîné d'un coup de sac isotherme.", "jab", hits=2, dmg=3),
   "Ps": L("Kick de béquille", "Kick de béquille violent vers l'avant.", "kick", dmg=6, angle=15, bkb=12),
   "Pd": L("Ticket coupant", "Ticket de caisse coupant au niveau des chevilles.", "sweep", dmg=4, angle=60),
   "PairN": L("Uppercut de casque", "Uppercut de casque en l'air.", "uppercut", dmg=5, angle=80),
   "PairS": L("Coup de sac aérien", "Coup de sac isotherme en l'air.", "hook", dmg=5),
   "PairD": L("Roue avant plongeante", "Roue avant plongeante.", "airdown", dmg=6, angle=-55),
   "Sn": S("Pizza frisbee", "Projectile droit et très rapide pour interrompre les actions.", "throw", kind="projectile",
           dmg=10, angle=30, bkb=20, kbs=0.4, startup=0.18, proj=proj(speed=95, life=0.9, size=1.4, shape="Cyl", color="#f5b041", mat="Plastic")),
   "Ss": S("Rush trottinette", "Dash percutant traversant une grande partie de l'arène.", "dash", kind="dash", speed=72, dur=0.45,
           dmg=13, angle=25),
   "Sd": S("Colis « Livré ! »", "Dépose un colis piégé qui explose en confettis avec un léger délai.", "trap", kind="trap",
           life=1.1, delay=1.0, radius=6, trapSize=(1.5, 1.5), dmg=14, angle=70, vfx="#ff6b6b"),
   "Sup": S("Wheelie", "Cabre sa trottinette vers le haut, la roue avant frappant en remontant.", "recovery", dmg=10, angle=80,
            bkb=18, kbs=0.3, **rec(76, 12)),
   "SairD": S("Livraison parachutée", "Tombe en piqué rectiligne, debout sur son sac isotherme.", "groundpound", dmg=14, angle=55,
              **gp(-110, 0, 6)),
  }},
 {"key": "bernard", "num": 4, "name": "Bernard du Guichet", "style": "Contrôle", "diff": 3, "launch": False,
  "weapon": "Tampon Géant & Dossiers", "passive": "paperasse", "passiveName": "Paperasse",
  "passiveDesc": "Chaque touche colle un formulaire. À 3 formulaires, l'adversaire est « en attente » : ralenti 2 s.",
  "weight": 1.0, "arena": "mairie",
  "moves": {
   "Pn": L("Mug + agrafeuse", "Coup de mug enchaîné d'un coup d'agrafeuse.", "jab", hits=2, dmg=3),
   "Ps": L("Classeur claqué", "Classeur claqué lourdement vers l'avant.", "hook", dmg=6, bkb=12),
   "Pd": L("Trombone géant", "Trombone géant piquant les pieds.", "sweep", dmg=4),
   "PairN": L("Tampon aérien", "Coup de tampon de haut en bas.", "overhead", dmg=6, angle=-40),
   "PairS": L("« Suivant ! »", "Repousse l'adversaire.", "cast", dmg=4, bkb=18, kbs=0.05, angle=10),
   "PairD": L("Pied de chaise de bureau", "Pied de chaise vers le bas.", "airdown", dmg=5, angle=-55),
   "Sn": S("Avion en papier", "Projectile qui colle automatiquement un formulaire au contact.", "throw", kind="projectile",
           dmg=10, angle=30, extraForms=1, proj=proj(speed=55, life=1.6, size=1.2, shape="Block", color="#ffffff", mat="Plastic")),
   "Ss": S("Tampon REFUSÉ", "Gros coup de tampon chargé vers l'avant qui renverse l'adversaire.", "overhead", dmg=16, bkb=30, kbs=0.6,
           angle=35, startup=0.34, hb=(5.5, 5.0), off=(2.8, 0.6)),
   "Sd": S("File d'attente", "Invoque une silhouette qui bloque le prochain projectile (bouclier).", "cast", kind="wall", life=4,
           wallSize=(1.2, 6), dmg=0, solid=False, vfx="#95a5a6"),
   "Sup": S("Pile de dossiers", "Une pile de dossiers monte du bas de l'écran, Bernard s'assoit dessus.", "recovery", dmg=8, angle=85,
            bkb=16, kbs=0.25, **rec(74, 0)),
   "SairD": S("Plongeon de dossier", "Se laisse tomber lourdement avec les bras chargés d'archives.", "groundpound", dmg=13, angle=50,
              **gp(-100, 0, 6.5)),
  }},
 {"key": "chef", "num": 5, "name": "Chef Flambé", "style": "Polyvalent", "diff": 2, "launch": False,
  "weapon": "Poêle & Rouleau à pâtisserie", "passive": "cuisson", "passiveName": "Cuisson",
  "passiveDesc": "Ses attaques de feu laissent une brûlure : +1 % toutes les 0,5 s pendant 3 s.", "weight": 1.0, "arena": "cuisine",
  "moves": {
   "Pn": L("Louche & fouet", "Coups rapides de louche et de fouet.", "jab", hits=3, dmg=2),
   "Ps": L("Poêle frontale", "Violent coup de poêle frontal.", "hook", dmg=6, angle=25, bkb=13),
   "Pd": L("Balayage de tablier", "Balayage avec le tablier pour faire trébucher.", "sweep", dmg=4, angle=70),
   "PairN": L("Coup de couvercle", "Couvercle qui tournoie.", "spin", dmg=5),
   "PairS": L("Retourné de crêpe", "Retourne l'adversaire comme une crêpe.", "uppercut", dmg=5, angle=70),
   "PairD": L("Sabot plongeant", "Coup de sabot vers le bas.", "airdown", dmg=5, angle=-55),
   "Sn": S("Crêpe volante", "Projectile planant avec une trajectoire imprévisible.", "throw", kind="projectile", dmg=11, angle=35,
           proj=proj(speed=42, life=2.0, size=1.6, shape="Cyl", color="#f8c471", mat="Plastic", wobble=True)),
   "Ss": S("Flambage", "Crache un jet de flammes court mais très large (applique Brûlure).", "cast", hb=(6.0, 4.5), off=(3.2, 0.6),
           hits=3, dmg=12, angle=35, status="burn", statusDur=3, vfx="#ff5a00"),
   "Sd": S("Oignon émincé", "Coupe un oignon. L'adversaire proche pleure (écran flou 1,5 s).", "trap", kind="aura", radius=6.5,
           dmg=6, bkb=10, kbs=0.2, angle=60, status="blind", statusDur=1.5, vfx="#d7bde2"),
   "Sup": S("Sauté à la poêle", "Se sert de sa poêle géante pour rebondir sur l'air et remonter.", "recovery", dmg=8, angle=80,
            bkb=16, kbs=0.25, **rec(76, 10)),
   "SairD": S("Pluie de spaghettis", "Chute lourde qui ligote brièvement les ennemis au sol.", "groundpound", dmg=10, angle=45,
              status="root", statusDur=1.0, **gp(-95, 0, 7)),
  }},
 {"key": "marcel", "num": 6, "name": "Marcel le Mime", "style": "Défense et pièges", "diff": 3, "launch": True,
  "weapon": "Accessoires invisibles", "passive": "murs", "passiveName": "Murs invisibles",
  "passiveDesc": "Jusqu'à 2 murs invisibles posés en même temps : ils bloquent projectiles et adversaires.",
  "weight": 0.95, "arena": "theatre",
  "moves": {
   "Pn": L("Fausse claque + canne invisible", "Fausse claque enchaînée d'un coup de canne invisible.", "jab", hits=2, dmg=3),
   "Ps": L("Corde invisible", "Tire une corde invisible, attirant légèrement l'adversaire pour un combo.", "thrust", dmg=4, pull=True,
           hb=(7.5, 2.4), off=(4.0, 0.5)),
   "Pd": L("Marche d'escalier invisible", "Marche d'escalier invisible frappant les pieds.", "stomp", dmg=4, angle=60),
   "PairN": L("Parapluie invisible", "Parapluie invisible qui tourne.", "spin", dmg=4, hits=2),
   "PairS": L("Ballon éclaté", "Fait éclater un ballon invisible.", "cast", dmg=5, angle=30),
   "PairD": L("Ascenseur qui descend", "Mime un ascenseur qui descend.", "airdown", dmg=5, angle=-60),
   "Sn": S("Mur invisible", "Pose un mur qui bloque instantanément les projectiles et les dashs.", "cast", kind="wall", life=5,
           wallSize=(1.2, 7), dmg=0, solid=True, maxWalls=2, startup=0.18, vfx="#e8f8ff"),
   "Ss": S("Tir à la corde", "Lance un lasso invisible. S'il touche, tire l'ennemi brusquement vers lui.", "throw", kind="projectile",
           dmg=8, bkb=30, kbs=0.0, pull=True, proj=proj(speed=85, life=0.38, size=1.0, color="#e8f8ff", tr=0.6)),
   "Sd": S("Contre silencieux", "Parade. S'il est frappé, encaisse sans dégât et riposte violemment.", "counter", kind="counter",
           window=0.6, dmg=16, bkb=32, kbs=0.6, angle=35),
   "Sup": S("Échelle invisible", "Mime l'ascension rapide d'une échelle (hitbox verticale active).", "recovery", dmg=9, angle=88,
            bkb=18, kbs=0.25, hb=(3.0, 8.0), off=(0.5, 2.5), **rec(80, 0)),
   "SairD": S("Le Piano", "Lâche un poids massif imaginaire. Effet sonore lourd à l'impact au sol.", "groundpound", dmg=16, angle=55,
              **gp(-120, 0, 6.5)),
  }},
 {"key": "bebe", "num": 7, "name": "Bébé Colosse", "style": "Choppeur", "diff": 2, "launch": False,
  "weapon": "Hochet Géant & Couche", "passive": "caprice", "passiveName": "Caprice",
  "passiveDesc": "Les coups reçus remplissent la jauge. Pleine : crise de larmes et super-armure 5 s.", "weight": 1.35, "arena": "creche",
  "moves": {
   "Pn": L("Hochet gauche-droite", "Coups maladroits de hochet gauche-droite.", "jab", hits=2, dmg=4),
   "Ps": L("Coup de fesse/couche", "Violent coup de fesse vers l'avant.", "bodyslam", dmg=6, bkb=13),
   "Pd": L("Roulade à quatre pattes", "Esquive basse et frappe.", "dash", kind="dash", speed=30, dur=0.25, dmg=5, angle=40),
   "PairN": L("Coup de tétine", "Coup de tétine.", "jab", dmg=4),
   "PairS": L("Jet de purée", "Purée lancée qui ralentit.", "throw", kind="projectile", dmg=4, status="slow", statusDur=1.5,
              proj=proj(speed=55, life=0.6, size=1.0, color="#f9e79f", mat="Plastic")),
   "PairD": L("Atterrissage fesses lourd", "Retombe sur les fesses.", "airdown", dmg=7, angle=-60, recovery=0.25),
   "Sn": S("Hurlement", "Onde de choc sonore autour de lui qui repousse fortement.", "roar", kind="aura", radius=8, dmg=10, bkb=30,
           kbs=0.45, angle=30, vfx="#aed6f1"),
   "Ss": S("Charge 4 pattes", "Fonce au sol, saisit l'adversaire (Chope) et le jette derrière lui.", "dash", kind="dash", speed=46,
           dur=0.45, dmg=13, angle=135, extra="throwBack"),
   "Sd": S("Colère sismique", "Frappe le sol des poings, créant un séisme de courte portée.", "stomp", kind="aura", radius=7, dmg=12,
           angle=78, vfx="#a0522d"),
   "Sup": S("Saut du lit", "Rebondit sur un lit à barreaux élastique qui apparaît sous lui.", "recovery", dmg=8, angle=85, bkb=18,
            kbs=0.25, **rec(84, 0)),
   "SairD": S("Plongeon Dodo", "Tombe lourdement sur le ventre, s'endormant une fraction de seconde à l'impact.", "groundpound",
              dmg=15, angle=50, recovery=0.6, **gp(-105, 0, 7.5)),
  }},
 {"key": "gloria", "num": 8, "name": "Gloria Zumba", "style": "Rythme", "diff": 3, "launch": False,
  "weapon": "Enceinte Fluo & Jambières", "passive": "tempo", "passiveName": "Tempo",
  "passiveDesc": "Un métronome bat toutes les 0,6 s. Une attaque lancée sur le temps fait +30 % de dégâts.", "weight": 0.95,
  "arena": "fitness",
  "moves": {
   "Pn": L("Clap + high kick", "Clap en rythme suivi d'un high kick.", "kick", hits=2, dmg=3),
   "Ps": L("Coude salsa", "Coude salsa avec une bonne avancée corporelle.", "thrust", dmg=5),
   "Pd": L("Twist balayé", "Twist balayé au niveau du sol.", "sweep", dmg=4),
   "PairN": L("Saut étoile", "Saut étoile (hitbox large).", "spin", dmg=4, hb=(8.0, 7.0)),
   "PairS": L("Ciseaux aériens", "Ciseaux aériens.", "airkick", hits=2, dmg=3),
   "PairD": L("Squat-punch descendant", "Squat-punch vers le bas.", "airdown", dmg=5, angle=-55),
   "Sn": S("Onde de basse", "Pose son enceinte qui crache un projectile sonore rectiligne.", "cast", kind="projectile", dmg=11,
           proj=proj(speed=65, life=1.2, size=2.0, color="#39ff14")),
   "Ss": S("Pas de conga", "Danse agressive vers l'avant frappant 3 fois de suite (multi-hit).", "dash", kind="dash", speed=28,
           dur=0.6, hits=3, dmg=4, angle=35),
   "Sd": S("Piétinement cardio", "Onde de choc au sol centrée sur elle-même.", "stomp", kind="aura", radius=7, dmg=11, angle=70,
           vfx="#ff4fa3"),
   "Sup": S("Saut pom-pom", "Grande pirouette verticale ascendante, propulsée par le son de l'enceinte.", "spin", dmg=9, angle=85,
            bkb=16, kbs=0.25, **rec(80, 4)),
   "SairD": S("Boule à facettes", "Tombe sur une boule disco. Aveugle très brièvement à l'impact.", "groundpound", dmg=12, angle=50,
              status="blind", statusDur=0.6, **gp(-100, 0, 6.5)),
  }},
 {"key": "lola", "num": 9, "name": "Lola Filtre", "style": "Zoneuse", "diff": 2, "launch": False,
  "weapon": "Perche à selfie & Ring Light", "passive": "likes", "passiveName": "Likes",
  "passiveDesc": "Chaque touche rapporte des likes. À 1000 likes : mode « Virale », dégâts et projectiles boostés 8 s.",
  "weight": 0.9, "arena": "studio",
  "moves": {
   "Pn": L("Smartphone + flash", "Coup de smartphone suivi d'un flash éblouissant.", "jab", hits=2, dmg=3),
   "Ps": L("Estoc de perche", "Coup d'estoc avec la perche à selfie (longue portée).", "thrust", dmg=5, hb=(8.0, 2.2), off=(4.5, 0.6)),
   "Pd": L("Glissade pose photo", "Glissade « pose photo » élégante.", "sweep", dmg=4),
   "PairN": L("Coup de Ring Light", "Coup de Ring Light.", "spin", dmg=4),
   "PairS": L("Kick compensé", "Kick avec talon compensé.", "airkick", dmg=5),
   "PairD": L("Perche plongeante", "Perche plongeante.", "airdown", dmg=5, angle=-55),
   "Sn": S("Le Flash", "Écran blanc localisé étourdissant l'ennemi pendant 0,5 s pour placer un combo.", "cast", hb=(5.0, 5.0),
           off=(2.8, 0.6), dmg=6, bkb=8, kbs=0.1, angle=20, status="stun", statusDur=0.5, vfx="#ffffff"),
   "Ss": S("Hashtag", "Tire un gros # bleu flottant horizontalement.", "throw", kind="projectile", dmg=12,
           proj=proj(speed=55, life=1.4, size=1.8, shape="Block", color="#3498db")),
   "Sd": S("Filtre chien", "Piège. Applique des oreilles de chien à l'ennemi (portée réduite 3 s).", "trap", kind="trap", life=8,
           trapSize=(2.5, 2), dmg=4, bkb=4, kbs=0, angle=70, status="dog", statusDur=3, vfx="#a0522d"),
   "Sup": S("Drone Caméra", "S'accroche à son drone de vlog qui la tire en diagonale vers le haut.", "recovery", dmg=7, angle=70,
            bkb=16, kbs=0.2, **rec(68, 34)),
   "SairD": S("Pluie de cœurs", "Piqué générant une cascade de cœurs (génère des likes à l'impact).", "groundpound", dmg=11,
              angle=50, extraLikes=200, **gp(-95, 0, 6.5)),
  }},
 {"key": "jordan", "num": 10, "name": "Jordan « RageQuit »", "style": "Rushdown", "diff": 3, "launch": False,
  "weapon": "Manette filaire & Clavier", "passive": "rage", "passiveName": "Rage",
  "passiveDesc": "Les coups subis remplissent la jauge. Pleine : « Tilt » 6 s, +50 % de dégâts mais plus d'esquive.",
  "weight": 0.95, "arena": "chambre",
  "moves": {
   "Pn": L("Spam bouton", "Combo furieux de manette façon « Spam bouton ».", "jab", hits=4, dmg=1.5, active=0.16),
   "Ps": L("Clavier balancé", "Coup de clavier balancé à l'horizontale.", "hook", dmg=6),
   "Pd": L("Souris yo-yo", "Souris filaire lancée comme un yo-yo au ras du sol.", "sweep", dmg=4, hb=(7.5, 2.0), off=(3.6, -1.8)),
   "PairN": L("Coup de casque RGB", "Coup de casque RGB.", "spin", dmg=4),
   "PairS": L("Câble-fouet", "Câble-fouet en l'air.", "thrust", dmg=5),
   "PairD": L("Smash de manette", "Smash de manette à deux mains.", "overhead", dmg=6, angle=-60),
   "Sn": S("Paquet de chips", "Projectile explosant en un nuage de miettes grasses.", "throw", kind="projectile", dmg=12,
           proj=proj(speed=60, life=0.9, size=1.4, shape="Block", color="#f4d03f", explode=5)),
   "Ss": S("Speedrun", "Dash frénétique glissant sur les genoux (traverse l'adversaire).", "dash", kind="dash", speed=82, dur=0.32,
           dmg=12, angle=30, passThrough=True),
   "Sd": S("Câble tendu", "Tend son câble de manette au sol (piège trébuchant).", "trap", kind="trap", life=8, trapSize=(4, 1),
           dmg=6, bkb=14, kbs=0.15, angle=85, status="stun", statusDur=0.6, vfx="#111111"),
   "Sup": S("Rage Jump", "Cri de rage propulsant Jordan vers le haut (Ventilo RGB).", "recovery", dmg=9, angle=85, bkb=18,
            kbs=0.25, **rec(84, 6)),
   "SairD": S("Écran Bleu (BSOD)", "Tombe avec un écran de PC lourd, figeant l'adversaire 0,5 s à l'impact.", "groundpound", dmg=12,
              angle=50, status="stun", statusDur=0.5, **gp(-105, 0, 6.5)),
  }},
 {"key": "fraise", "num": 11, "name": "Dr Fraise", "style": "Contrôle", "diff": 2, "launch": False,
  "weapon": "Fraise géante & Miroir", "passive": "fourire", "passiveName": "Fou rire",
  "passiveDesc": "Le gaz hilarant empêche l'adversaire d'utiliser ses Signatures (S) pendant 3 s.", "weight": 1.0,
  "arena": "dentiste",
  "moves": {
   "Pn": L("Miroir + genou stérile", "Coup de miroir dentaire et genou stérile.", "jab", hits=2, dmg=3),
   "Ps": L("Fraise vrombissante", "Fraise vrombissante tenue en avant (multi-hit court).", "thrust", hits=4, dmg=1.5, active=0.2),
   "Pd": L("Fil dentaire lasso", "Fil dentaire tendu au sol façon lasso.", "sweep", dmg=4, pull=True),
   "PairN": L("Lampe aveuglante", "Lampe aveuglante.", "cast", dmg=4),
   "PairS": L("Pince plongeante", "Pince plongeante.", "airkick", dmg=5),
   "PairD": L("Coup de roulette de chaise", "Roulette de chaise vers le bas.", "airdown", dmg=5, angle=-55),
   "Sn": S("Gaz hilarant", "Bulle stationnaire infligeant le statut Fou Rire au contact.", "cast", kind="projectile", dmg=6, bkb=10,
           kbs=0.15, status="laugh", statusDur=3, proj=proj(speed=10, life=3.0, size=2.6, color="#d2b4de", tr=0.4, pierce=True)),
   "Ss": S("Fraise perforante", "Dash chargé perçant la garde avec la roulette géante.", "dash", kind="dash", speed=55, dur=0.4,
           dmg=14, angle=30),
   "Sd": S("Bain de bouche", "Crache une grande flaque bleue glissante au sol.", "trap", kind="trap", life=6, trapSize=(7, 1), dmg=3,
           bkb=6, kbs=0.05, angle=60, status="slip", statusDur=2.5, vfx="#5dade2"),
   "Sup": S("Fauteuil éjectable", "Un fauteuil de dentiste apparaît, le propulse en l'air et retombe.", "recovery", dmg=8, angle=85,
            bkb=16, kbs=0.25, **rec(88, 0)),
   "SairD": S("Pluie de dents", "Chute droite en semant des dents en sucre autour de lui.", "groundpound", dmg=12, angle=50,
              **gp(-100, 0, 7)),
  }},
 {"key": "sumo", "num": 12, "name": "Sumo Gélatine", "style": "Tank pour débutants", "diff": 1, "launch": True,
  "weapon": "Gants en Guimauve", "passive": "rebond", "passiveName": "Rebond",
  "passiveDesc": "Les attaquants au corps à corps rebondissent légèrement en arrière. Lourd : plus dur à éjecter.",
  "weight": 1.4, "arena": "dojo",
  "moves": {
   "Pn": L("Claques molles (Shiko)", "Grosses claques molles et poussée de paumes.", "jab", hits=3, dmg=2),
   "Ps": L("Ventre-rebond", "Coup de bedaine élastique.", "bodyslam", dmg=6, bkb=14),
   "Pd": L("Glissade gluante", "Glissade gluante sur le ventre.", "dash", kind="dash", speed=30, dur=0.3, dmg=5, angle=40),
   "PairN": L("Bras-ressort élastique", "Bras-ressort élastique.", "cast", dmg=5),
   "PairS": L("Coup de bide", "Coup de bide aérien.", "bodyslam", dmg=5),
   "PairD": L("Plat ventre amorti", "Plat ventre amorti.", "airdown", dmg=6, angle=-60),
   "Sn": S("Boulette de gelée", "Arrache un bout de son ventre et le lance (projectile ralentissant).", "throw", kind="projectile",
           dmg=10, status="slow", statusDur=2, proj=proj(speed=50, life=1.2, size=1.5, color="#7ee08a", mat="Plastic", tr=0.3)),
   "Ss": S("Charge Sumo", "Dash inarrêtable (Armure) écrasant l'adversaire.", "charge", kind="dash", speed=48, dur=0.5, armor=True,
           dmg=15, angle=30),
   "Sd": S("La Flaque", "Se liquéfie totalement (esquive les tirs) puis rejaillit en uppercut massif.", "uppercut", invuln=0.45,
           startup=0.45, dmg=14, angle=85, hb=(4.5, 6.0), off=(1.2, 1.5)),
   "Sup": S("Tremblote géante", "S'étire vers le ciel comme un ressort vert, frappant tout sur son passage.", "recovery", dmg=10,
            angle=88, bkb=20, kbs=0.3, hb=(4.5, 8.0), off=(0.5, 2.5), **rec(74, 0)),
   "SairD": S("Le Splash", "Bombe à eau. S'il touche le sol, projette de la gelée de part et d'autre.", "groundpound", dmg=14,
              angle=50, **gp(-100, 0, 9)),
  }},
 {"key": "ramses", "num": 13, "name": "Ramsès le Patraque", "style": "Usure", "diff": 2, "launch": False,
  "weapon": "Bandelettes & Thermomètre", "passive": "contagion", "passiveName": "Contagion",
  "passiveDesc": "L'adversaire touché éternue au hasard une fois dans les 3 s, ce qui annule son action.", "weight": 1.0,
  "arena": "tombeau",
  "moves": {
   "Pn": L("Coup de thermomètre géant", "Coup de thermomètre géant.", "thrust", dmg=5),
   "Ps": L("Mouchoir-fouet", "Mouchoir-fouet, claque l'adversaire à mi-distance.", "hook", dmg=5, hb=(6.0, 3.0), off=(3.2, 0.6)),
   "Pd": L("Bandelette traînante", "Bandelette traînante fouettant les chevilles.", "sweep", dmg=4, hb=(7.5, 2.0), off=(3.6, -1.8)),
   "PairN": L("Atchoum anti-air", "Éternuement vers le haut.", "cast", dmg=4, angle=80, off=(1.5, 2.0)),
   "PairS": L("Coup de pied plâtré", "Coup de pied plâtré.", "airkick", dmg=5),
   "PairD": L("Bandelette plongeante", "Bandelette plongeante.", "airdown", dmg=5, angle=-55),
   "Sn": S("Éternuement", "Nuage microbien à courte portée (applique Contagion garantie).", "cast", hb=(5.0, 4.5), off=(2.8, 0.6),
           dmg=9, angle=35, status="sneeze", statusDur=3, vfx="#abebc6"),
   "Ss": S("Grappin bandelette", "Lance son bras au loin, si touche, se tire vers l'ennemi.", "thrust", kind="projectile", dmg=9,
           bkb=12, kbs=0.2, angle=60, extra="grappleSelf", proj=proj(speed=90, life=0.4, size=0.8, shape="Block", color="#efe3c2", mat="Fabric")),
   "Sd": S("Mouchoirs usagés", "Sème 3 pièges contagieux au sol devant lui.", "trap", kind="trap", life=8, trapSize=(2, 1.5),
           count=3, dmg=3, bkb=4, kbs=0, angle=70, status="sneeze", statusDur=3, vfx="#fdfefe"),
   "Sup": S("Sortie de sarcophage", "S'enferme dans un sarcophage qui lévite brusquement en diagonale.", "recovery", dmg=8, angle=75,
            bkb=16, kbs=0.25, **rec(72, 26)),
   "SairD": S("Sirop gluant", "Chute lourdement en éclatant une fiole de sirop (ralentit la zone).", "groundpound", dmg=11, angle=50,
              status="slow", statusDur=2, **gp(-95, 0, 7)),
  }},
 {"key": "canard", "num": 14, "name": "Capitaine Canard", "style": "Aérien", "diff": 2, "launch": False,
  "weapon": "Bouée Canard & Pistolet à eau", "passive": "flottaison", "passiveName": "Flottaison",
  "passiveDesc": "Un saut aérien supplémentaire, et maintenir SAUT en tombant le fait planer.", "weight": 0.9,
  "arena": "piscine",
  "moves": {
   "Pn": L("Bouée + éclaboussure", "Coup de bouée caoutchouteux et éclaboussure.", "jab", hits=2, dmg=3),
   "Ps": L("Bec de bouée", "Bec de bouée tendu (coup de tête du plastique).", "bodyslam", dmg=5),
   "Pd": L("Glissade palmée", "Glissade palmée sur le ventre.", "dash", kind="dash", speed=32, dur=0.28, dmg=5, angle=40),
   "PairN": L("Jet d'eau court", "Jet d'eau court.", "cast", dmg=4),
   "PairS": L("Battement de palmes", "Battement de palmes.", "airkick", hits=2, dmg=3),
   "PairD": L("Plongeon bec", "Plongeon bec en piqué.", "airdown", dmg=6, angle=-60),
   "Sn": S("Coin-coin", "Onde sonore circulaire centrée sur lui qui étourdit 0,5 s.", "roar", kind="aura", radius=7, dmg=8,
           bkb=14, kbs=0.25, angle=40, status="stun", statusDur=0.5, vfx="#ffd400"),
   "Ss": S("Torpille canard", "Tourbillonne horizontalement propulsé par son pistolet à eau.", "spin", kind="dash", speed=64,
           dur=0.42, dmg=13, angle=30),
   "Sd": S("Piscine gonflable", "Déploie une mare d'eau bloquant les déplacements rapides.", "trap", kind="trap", life=6,
           trapSize=(7, 1.5), dmg=0, bkb=0, kbs=0, angle=0, status="slow", statusDur=1.5, persistent=True, vfx="#5dade2"),
   "Sup": S("Envol de bouée", "S'envole très haut sur un geyser, puis plane brièvement.", "recovery", dmg=7, angle=85, bkb=14,
            kbs=0.2, glide=True, **rec(96, 4)),
   "SairD": S("Bombe à eau", "Chute les genoux repliés (faire la bombe), grande zone d'éclaboussure.", "airdown", dmg=13, angle=50,
              **gp(-100, 0, 9)),
  }},
 {"key": "gaston", "num": 15, "name": "Gaston le Magnifique", "style": "Aléatoire", "diff": 3, "launch": False,
  "weapon": "Baguette de Magie & Chapeau", "passive": "tours", "passiveName": "Tours ratés",
  "passiveDesc": "Le Tour aléatoire tire 1 effet sur 3 : Colombe (projectile), Confettis (explosion), Lapin (gros coup). L'icône du prochain est affichée.",
  "weight": 0.95, "arena": "cabaret",
  "moves": {
   "Pn": L("Baguette + foulard sans fin", "Coup de baguette crépitante enchaîné d'un foulard sans fin.", "jab", hits=2, dmg=3),
   "Ps": L("Cartes tranchantes", "Cartes tranchantes projetées en éventail court.", "throw", hb=(6.0, 3.0), off=(3.2, 0.6), dmg=5),
   "Pd": L("Chaussure vernie", "Chaussure vernie en balayage magique.", "sweep", dmg=4),
   "PairN": L("Cape tournoyante", "Cape tournoyante.", "spin", dmg=4, hits=2),
   "PairS": L("Disparition ratée", "Disparition ratée.", "airkick", dmg=5),
   "PairD": L("Chapeau plongeant", "Chapeau plongeant.", "airdown", dmg=5, angle=-55),
   "Sn": S("Tour aléatoire", "Déclenche l'effet du passif au bout de sa baguette (courte portée).", "cast", dmg=11, extra="randomTrick",
           vfx="#f7dc6f"),
   "Ss": S("Passe-passe", "Dash de téléportation courte. S'il traverse un ennemi, l'étourdit.", "dash", kind="dash", speed=90,
           dur=0.18, dmg=7, bkb=8, kbs=0.1, angle=20, status="stun", statusDur=0.6, passThrough=True, vfx="#8e44ad"),
   "Sd": S("Trappe", "Un trou s'ouvre au sol. L'ennemi tombe et est éjecté du haut de l'écran.", "trap", kind="trap", life=6,
           trapSize=(3, 1.5), dmg=12, bkb=40, kbs=0.3, angle=90, vfx="#111111"),
   "Sup": S("Lévitation ratée", "Le lapin du chapeau le tire violemment vers le haut par les oreilles.", "recovery", dmg=8,
            angle=85, bkb=16, kbs=0.25, **rec(88, 0)),
   "SairD": S("Pluie de colombes", "Chute piquée tout en lâchant des colombes éblouissantes.", "groundpound", dmg=11, angle=50,
              status="blind", statusDur=0.8, **gp(-95, 0, 7)),
  }},
 {"key": "bob", "num": 16, "name": "Gros Bob", "style": "Choppeur", "diff": 2, "launch": False,
  "weapon": "Glacière & Tongs", "passive": "fraicheur", "passiveName": "Fraîcheur",
  "passiveDesc": "La jauge baisse quand il bouge et remonte à l'arrêt. Au-dessus de 70 %, ses coups ont 30 % de chance de geler.",
  "weight": 1.35, "arena": "plage",
  "moves": {
   "Pn": L("Double claque poilue", "Double claque poilue très lourde.", "jab", hits=2, dmg=4),
   "Ps": L("Coup de glacière", "Grand coup de glacière balancée par l'anse.", "hook", dmg=7, bkb=13),
   "Pd": L("Glissade sur glace", "Glissade sur glace (coup de tong bas).", "sweep", dmg=4),
   "PairN": L("Parasol ouvert", "Ouvre un parasol.", "spin", dmg=5),
   "PairS": L("Pied de yéti volant", "Pied de yéti volant.", "airkick", dmg=6),
   "PairD": L("Avalanche de ventre", "Avalanche de ventre.", "airdown", dmg=6, angle=-60),
   "Sn": S("Boule de neige", "Crache un gros projectile de glace droit devant (ralentit).", "throw", kind="projectile", dmg=11,
           status="slow", statusDur=2, proj=proj(speed=55, life=1.3, size=1.8, color="#ffffff", mat="Ice")),
   "Ss": S("Charge en luge", "S'assoit sur sa glacière et fonce, repoussant tout avec super-armure.", "charge", kind="dash",
           speed=50, dur=0.5, armor=True, dmg=14, angle=30),
   "Sd": S("Mur de glace / Granita", "Crée une barricade glacée (remonte sa Jauge de Fraîcheur).", "cast", kind="wall", life=5,
           wallSize=(1.5, 5), dmg=0, solid=True, extra="refillFresh", vfx="#aed6f1"),
   "Sup": S("Avalanche ascendante", "Propulsé vers le haut par une petite éruption de neige.", "recovery", dmg=9, angle=85, bkb=18,
            kbs=0.25, **rec(76, 6)),
   "SairD": S("Pluie de Grêlons", "Tombe assis sur sa glacière, des glaçons tombant autour de lui.", "groundpound", dmg=14,
              angle=50, **gp(-100, 0, 8)),
  }},
 {"key": "robo", "num": 17, "name": "R-0B0", "style": "Anti-projectiles", "diff": 2, "launch": False,
  "weapon": "Tuyau flexible & Brosse rotative", "passive": "reservoir", "passiveName": "Réservoir",
  "passiveDesc": "L'Aspiration avale les projectiles adverses ; Recrachat les renvoie avec +50 % de vitesse.", "weight": 1.1,
  "arena": "appart",
  "moves": {
   "Pn": L("Pare-chocs + brosse", "Coups mécaniques de pare-chocs et brosse rotative.", "jab", hits=3, dmg=2),
   "Ps": L("Tuyau-poing", "Tuyau-poing s'étirant droit devant (très bonne allonge).", "thrust", dmg=5, hb=(8.5, 2.2), off=(4.6, 0.6)),
   "Pd": L("Balai rotatif", "Coup de balai rotatif au niveau du sol.", "sweep", hits=2, dmg=2.5),
   "PairN": L("Brosse tournoyante", "Brosse tournoyante.", "spin", hits=3, dmg=2),
   "PairS": L("Mode souffleur", "Souffle l'adversaire.", "cast", dmg=3, bkb=16, kbs=0.05, angle=10),
   "PairD": L("Tuyau plongeant", "Tuyau plongeant.", "airdown", dmg=5, angle=-55),
   "Sn": S("Aspiration", "Trou noir frontal. Attire les joueurs et avale les projectiles.", "cast", kind="vacuum", radius=10,
           dur=0.7, dmg=5, bkb=0, kbs=0, angle=0, pull=True, vfx="#2c3e50"),
   "Ss": S("Recrachat / Nettoyage", "Dash en zigzag si vide. Recrache un projectile mortel si plein.", "dash", kind="dash", speed=46,
           dur=0.45, dmg=11, angle=30, extra="spit"),
   "Sd": S("Sac à poussière", "Libère un nuage aveuglant autour de lui.", "roar", kind="aura", radius=7, dmg=5, bkb=10, kbs=0.15,
           angle=50, status="blind", statusDur=1.5, vfx="#a6acaf"),
   "Sup": S("Turbo vertical", "Propulseur de poussière le projetant violemment vers le haut.", "recovery", dmg=9, angle=88,
            bkb=18, kbs=0.25, **rec(90, 0)),
   "SairD": S("Chute du disque", "Rentre ses bras et tombe comme un poids mort en acier (très lourd).", "groundpound", dmg=16,
              angle=55, **gp(-125, 0, 7)),
  }},
 {"key": "papi", "num": 18, "name": "Papi DJ", "style": "Zoneur sonore", "diff": 2, "launch": False,
  "weapon": "Vinyles Tranchants & Platine", "passive": "playlist", "passiveName": "Playlist",
  "passiveDesc": "Le Drop des basses change de piste : Rap = vitesse, Slow = soin léger, Techno = dégâts.", "weight": 0.95,
  "arena": "village",
  "moves": {
   "Pn": L("Vinyle dague + charentaise", "Coup de vinyle comme une dague, enchaîné d'un coup de charentaise.", "jab", hits=2, dmg=3),
   "Ps": L("Scratch", "Double frappe en se dandinant.", "hook", hits=2, dmg=3),
   "Pd": L("Câble jack", "Câble jack fouettant les chevilles.", "sweep", dmg=4, hb=(7.0, 2.0), off=(3.4, -1.8)),
   "PairN": L("Casque balancé", "Casque balancé.", "spin", dmg=4),
   "PairS": L("Saut de scène", "Saut de scène.", "airkick", dmg=5),
   "PairD": L("Vinyle plongeant", "Vinyle plongeant.", "airdown", dmg=5, angle=-55),
   "Sn": S("Vinyle-boomerang", "Lance un disque qui fait l'aller-retour.", "throw", kind="projectile", dmg=11,
           proj=proj(speed=60, life=1.6, size=1.4, shape="Cyl", color="#111111", mat="Plastic", boomerang=True)),
   "Ss": S("Drop des basses", "Onde de choc horizontale poussant l'ennemi. (Change la piste du Passif).", "cast", kind="projectile",
           dmg=12, extra="nextTrack", proj=proj(speed=50, life=0.9, size=3.0, color="#8e44ad", tr=0.4, pierce=True)),
   "Sd": S("Mur d'enceintes", "Fait jaillir deux énormes baffles bloquant tout projectile.", "cast", kind="wall", life=5,
           wallSize=(2.0, 5), dmg=0, solid=True, vfx="#1c2833"),
   "Sup": S("Slam", "Se jette en l'air comme dans une foule imaginaire.", "recovery", dmg=8, angle=85, bkb=16, kbs=0.25,
            **rec(78, 10)),
   "SairD": S("Rewind Drop", "Tombe très vite, et s'il rate, revient instantanément à sa hauteur initiale.", "groundpound", dmg=13,
              angle=50, extra="rewind", **gp(-130, 0, 6)),
  }},
 {"key": "pigeon", "num": 19, "name": "Le Roi Pigeon", "style": "Invocateur", "diff": 3, "launch": True,
  "weapon": "Baguette de Pain & Nuée", "passive": "nuee", "passiveName": "Nuée",
  "passiveDesc": "Génère un pigeon toutes les 2 s (6 max). Les Signatures consomment un pigeon ; sans pigeon elles font 30 % de dégâts en moins.",
  "weight": 0.95, "arena": "place",
  "moves": {
   "Pn": L("Pied royal + picorage", "Coup de pied royal et picorage rapide.", "kick", hits=2, dmg=3),
   "Ps": L("Baguette en estoc", "Baguette en estoc (épée longue).", "thrust", dmg=5, hb=(8.0, 2.4), off=(4.4, 0.6)),
   "Pd": L("Miettes glissantes", "Miettes glissantes balayées sous le pied.", "sweep", dmg=3, status="slip", statusDur=1.2),
   "PairN": L("Battement d'ailes", "Battement d'ailes.", "spin", dmg=4),
   "PairS": L("Serres de pigeon", "Serres de pigeon.", "airkick", dmg=5),
   "PairD": L("Piqué de baguette", "Piqué de baguette.", "airdown", dmg=5, angle=-55),
   "Sn": S("Pigeon chercheur", "Envoie 1 pigeon lent à tête chercheuse (suit l'adversaire).", "throw", kind="projectile", dmg=10,
           proj=proj(speed=32, life=3.0, size=1.2, color="#95a5a6", mat="Plastic", homing=True)),
   "Ss": S("Charge de la Nuée", "La nuée forme une pointe de lance et dash vers l'avant.", "dash", kind="dash", speed=58, dur=0.4,
           dmg=13, angle=30),
   "Sd": S("Jet de miettes", "Jette des miettes au sol. La nuée fond agressivement sur la zone (piège).", "trap", kind="trap",
           life=1.0, delay=0.8, radius=6, trapSize=(2, 1), dmg=12, angle=70, vfx="#d4a056"),
   "Sup": S("Envol porté", "Ses pigeons l'attrapent par la cape et le hissent très haut (sans hitbox).", "recovery", dmg=0,
            nohit=True, **rec(98, 6)),
   "SairD": S("Piqué collectif", "Plonge entouré de ses pigeons formant une perceuse redoutable.", "groundpound", hits=3, dmg=5,
              angle=50, **gp(-100, 0, 7)),
  }},
 {"key": "ventouse", "num": 20, "name": "Madame Ventouse", "style": "Mobilité", "diff": 2, "launch": False,
  "weapon": "Ventouse Géante & Clé à molette", "passive": "grappin", "passiveName": "Grappin",
  "passiveDesc": "Sa ventouse s'accroche aux murs et au-dessous des plateformes : elle s'y tire.", "weight": 1.0,
  "arena": "egouts",
  "moves": {
   "Pn": L("Clé à molette + botte", "Coup de clé à molette rapide et coup de botte.", "jab", hits=2, dmg=3),
   "Ps": L("Coup de tuyau", "Coup de tuyau balancé violemment à l'horizontale.", "hook", dmg=6),
   "Pd": L("Serre-joint", "Serre-joint écrasant les orteils.", "stomp", dmg=4),
   "PairN": L("Rodéo sur tuyau", "Rodéo sur tuyau.", "spin", dmg=4),
   "PairS": L("Ventouse frontale", "Ventouse frontale.", "thrust", dmg=5),
   "PairD": L("Glissade dans l'eau", "Glissade dans l'eau vers le bas.", "airdown", dmg=5, angle=-55),
   "Sn": S("Jet de fuite", "Ouvre une valve crachant un projectile d'eau en cloche.", "cast", kind="projectile", dmg=11, angle=45,
           proj=proj(speed=55, grav=50, up=0.5, life=1.4, size=1.4, color="#5dade2", tr=0.2)),
   "Ss": S("Ventouse grappin", "Tire sa ventouse. Si touche un joueur, l'attire. Si touche un mur, s'y tire.", "thrust",
           kind="projectile", dmg=8, bkb=30, kbs=0, pull=True, extra="grapple",
           proj=proj(speed=95, life=0.45, size=1.0, shape="Cyl", color="#c0392b", mat="Plastic")),
   "Sd": S("Inondation", "Crée une mare glissante envoyant valser l'adversaire (Renversement).", "trap", kind="trap", life=6,
           trapSize=(7, 1.5), dmg=8, bkb=20, kbs=0.2, angle=80, status="slip", statusDur=2, vfx="#5dade2"),
   "Sup": S("Ventouse plafond", "Tire le grappin vers le haut pour une récupération de hauteur extrême.", "recovery", dmg=7,
            angle=85, bkb=14, kbs=0.2, **rec(104, 0)),
   "SairD": S("Chute Ventouse", "Tombe la ventouse en avant, s'accroche au sol (Pop !) en créant une onde.", "groundpound", dmg=13,
              angle=50, **gp(-105, 0, 7.5)),
  }},
]

SLOTS = ["Pn", "Ps", "Pd", "PairN", "PairS", "PairD", "Sn", "Ss", "Sd", "Sup", "SairD"]
SLOT_LABEL = {
    "Pn": "P · Neutre", "Ps": "P · Côté (→)", "Pd": "P · Bas (↓)", "PairN": "P en l'air · Neutre", "PairS": "P en l'air · Côté",
    "PairD": "P en l'air · Bas", "Sn": "S · Neutre", "Ss": "S · Côté (→)", "Sd": "S · Bas (↓)", "Sup": "S · Remontée (↑)",
    "SairD": "S · Plongeon (↓ en l'air)",
}
